IgniteUI/indigo-design-docfx

en/components/grid-column-pinning.md
en/components/grid-filter.md
en/components/grid-paging.md
en/components/grid-summaries.md
en/components/grid.md
en/components/hyperlink.md
en/components/icon.md
en/components/input.md
en/components/list-custom.md
en/components/list.md
en/components/nav-drawer.md
en/components/navbar.md
en/components/progress.md
en/components/radio-group.md
en/components/slider.md
en/components/snackbar.md
en/components/switch.md
en/components/tabs.md
en/components/text.md
en/components/time-picker.md
en/components/toast.md

All components drafts have been reviewed by Sarah and changes are in

Sarah components

---

en/components/avatar.md
en/components/badge.md
en/components/bottom-nav.md
en/components/button-group.md
en/components/button.md
en/components/calendar.md
en/components/cards-custom.md
en/components/cards.md
en/components/carousel.md
en/components/chart-category.md
en/components/checkbox.md
en/components/dialog.md
en/components/hyperlink.md
en/components/progress.md
en/components/radio-group.md
en/components/snackbar.md
en/components/toast.md

Made some changes to the way pseudocode is formatted in codegen sections, after discussing them with Karl.
Fixed the issues submitted by Sarah upon reviewing the content of the pages for one part of the components.
Closes #7, closes #8, closes #9, closes #10, closes #11, closes #12, closes #13, closes #14, closes #16, closes #17, closes #18, closes #19, closes #20.

Code formatting and 

---

jp/getting-started.md

First draft of getting started topic.
I also tried to indent some lines to see if it would fix the issue I logged about numbering being reset.

Getting Started topic

---

en/known-issues.md
en/patterns/card-collection.md
en/patterns/checkbox-group.md
en/patterns/details.md
en/patterns/file-upload.md
en/patterns/form.md
en/patterns/image-manipulation.md
en/patterns/lists.md
en/patterns/user-profile.md

Patterns topics update after Sarah's review

Patterns edits

---

jp/patterns/av.md
jp/patterns/avatar+badge.md
jp/patterns/card-collection.md
jp/patterns/checkbox-group.md
jp/patterns/details.md
jp/patterns/file-upload.md
jp/patterns/form.md
jp/patterns/gallery.md
jp/patterns/image-manipulation.md
jp/patterns/lists.md
jp/patterns/user-profile.md
jp/sidebar-toc/toc.yml

Added 11 patterns topics and updated the TOC.

Added patterns first draft

---

en/getting-started.md
jp/getting-started.md

They shouldn't go up one level because the topic is already at the root level.
This should fix #86.

Fixed image paths

---

jp/components/time-picker.md

This change was made in English but not in Japanese, so I am making it in the Japanese topic.
Related to #109.

Removed second row of images

---

package-lock.json
package.json

Update igniteui-docfx-template to version 1.0.7

---

jp/getting-started.md

Added new notes

---

jp/components/input.md
jp/style/colors.md

Added new content from PR133

---

package-lock.json

Fixed broken build

---

en/getting-started.md
jp/getting-started.md

I decided to add the link in a separate pull request as I do not agree with the TOC changes in #145.
https://github.com/IgniteUI/indigo-design-docfx/pull/145/commits/1e298d3d5b65f97cb236f9ee672040fb32f27d63
If that pull request will be closed without merging, you can add the English link in this branch as well.

Added a download link

---

en/codegen/after-codegen.md
en/known-issues.md

Adding components that we have not implemented generators for in this release in the known issues topic.
Also added missing font import in the after-codegen topic.

adding missing components, adding missing font

---

en/known-issues.md

I also adjusted the wording for the not supported section.

Button text in form patterns will not be correct

---

jp/best-layout-practices.md

Fixed note styling

---

en/known-issues.md

Spelling and Link Fixes

---

jp/getting-started.md

Fixed only in Japanese as the English getting started topic will no longer be used.

Fixed links in getting started topic

---

en/codegen/vscode-plugin.md

adding a note about long initial start up for first time use

Rob update plugin topic

---

en/codegen/vscode-plugin.md
jp/codegen/vscode-plugin.md

adding explicit requirement that Sketch files must have Indigo.Design UI Kit components in order to generate
also fixing incorrect links

fixing incorrect links and added another requirement

---

package-lock.json
package.json

The update includes:
- header and footer fixes
- TOC fixes

Update ignite ui docfx template to 1.0.13-beta.1

---

en/prototyping/interaction-options.md

Aww... no more hotpot
Fixes #169.

Fixed metadata typo

---

jp/video-tutorials.md

Updated video link

---

package-lock.json
package.json

More information what's in the update [here](https://github.com/IgniteUI/igniteui-docfx-template/releases/tag/v1.0.13).

Updated igniteui-docfx-template to version 1.0.13

---

jp/components/calendar.md
jp/components/input.md

Updated calendar and input topics for v1.0.2

---

jp/components/calendar.md

Removed an extra row from the table

---

jp/sidebar-toc/toc.yml
jp/video-tutorials.md

Updated about half of the video links to ones in Japanese.
Removed the (English) reminder from the title of the topic and the TOC.
Added the (English) reminder to the remaining videos that are still in English.

Updated video links

---

jp/creating-an-artboard.md

Fixed artboard links

---

en/components/avatar.md
en/components/badge.md
en/components/bottom-nav.md
en/components/button-group.md
en/components/carousel.md
en/components/chart-category.md
en/components/checkbox.md
en/components/grid.md
en/components/input.md
en/components/list.md
en/components/progress.md
en/components/radio-group.md
en/components/slider.md
en/components/snackbar.md
en/components/switch.md
en/components/toast.md

fixing various inconsistencies and adding more information about the DataProperty to the Input component as well as some other minor changes.

Rob databinding

---

package-lock.json
package.json

Adding navigation search improvements.

Updated igniteui-docfx-template to 1.1.1

---

en/docfx.json
gulpfile.js
jp/docfx.json
package-lock.json
package.json

Updating indigo-design-docfx to be compatible with docfx-template.

---

en/style/typography.md
jp/style/typography.md

Fixing broken links and removing reference to deprecated Text components from jp
Closes #253

Fixing broken links

---

en/global.json
jp/global.json

Adding global variables containg the github links for every version

---

en/components/cards.md
en/creating-an-artboard.md
en/getting-started.md
en/global.json
en/prototyping/creating-a-prototype.md
en/prototyping/interaction-options.md
en/prototyping/setting-up-a-usability-study.md
en/prototyping/usability-study-results-overview.md
en/prototyping/workspaces.md
jp/components/cards.md
jp/creating-an-artboard.md
jp/getting-started.md
jp/global.json
jp/prototyping/creating-a-prototype.md
jp/prototyping/interaction-options.md
jp/prototyping/setting-up-a-usability-study.md
jp/prototyping/usability-study-results-overview.md
jp/prototyping/workspaces.md

Updated page links and image URLs that were redirecting to use the true source of the resource. This is for our overall SEO effort.

Updated redirecting URLs to true source for SEO boost

---

en/codegen/vscode-plugin.md
en/prototyping/interaction-options.md
jp/codegen/vscode-plugin.md

fix(images): apply responsive-img class to missed images

---

en/global.json
jp/global.json

Adding global variables for theme enabling/disabling

---

package-lock.json
package.json

Updating Docfx Template to 2.0.21 version

---

en/codegen/layout-codegen.md
en/components/grid-toolbar.md
en/components/grid.md
en/components/hierarchical-grid.md
en/components/tree-grid.md

added code gen stuff for grid, hierarchical grid and tree grid and made some adjustments to the layout topic regarding the grid width and height behavior.

merge rs-code-gen into si-grid-features

---

en/global.json
jp/global.json

Adding demos base url var

---

en/style/colors.md
en/style/illustrations.md
en/style/typography.md

Fixes styling issues for warning overlay element

Closes #291 styling bug

---

package-lock.json
package.json

Upgrade docfx-template to 2.3.1

---

en/components/grid.md
jp/components/grid.md

Fix broken link

---

gulpfile.js
package-lock.json
package.json

Closes #303 
When you test this PR, check if the watcher is working correctly

Update gulp to version 4

---

en/global.json
jp/global.json

Updated KR domains to utilize new domain -- infragistics.co.kr

Updated KR domains to infragistics.co.kr

---

web.config

Remove file extension json type

---

en/docfx.json
jp/docfx.json

Related to https://github.com/IgniteUI/igniteui-docfx/issues/1878

Enabling cache clear

---

jp/codegen/after-codegen.md

Revising translation in After Code Generation topic.

---

jp/prototyping/set-up-a-user-test.md

Adding a missing sentence to the _Set up a user test_ topic in JP.

Adding a missing sentence to match the changes from #325

---

package-lock.json
package.json

Update template version -vnext

---

en/sidebar-toc/toc.yml

added "new" label and Camel Case for AppBuilder sections

Update toc labels and section names AppBuilder

---

gulpfile.js
package-lock.json
package.json

Fixing errors and update templ to 2.9.4

---

en/environment.json
jp/environment.json

Fix gtm tracking -master

---

en/global.json
en/index.md
en/web.config
jp/global.json
jp/index.md
jp/web.config
package-lock.json
package.json

Update to SPA and global search -vnext

---

en/global.json
en/index.md
en/web.config
jp/global.json
jp/index.md
jp/web.config
package-lock.json
package.json

Update to SPA and global search -master

---

en/known-issues.md
en/style/typography.md

- Add info on typography parsing.
- Add info on non-resizable components.
- Remove old no longer valid known issues.

Update docs for 3.2.0

---

en/sidebar-toc/toc.yml

TOC changes

---

en/appbuilder/generate-app/run-application-locally.md
en/appbuilder/preview-code.md
en/appbuilder/single-page-apps-and-navigation.md
en/codegen/after-codegen.md
en/components/banner.md
en/components/card.md
en/components/linear-gauge.md
en/components/text.md
en/getting-started-old.md
en/getting-started.md
en/global.json
en/style/illustrations.md
en/sync-themes-plugin.md
package-lock.json
package.json

Add useWarningsAsErrors option

---

en/appbuilder/app-themes/app-themes.md
en/appbuilder/flex-layouts/flex-layouts.md
en/appbuilder/generate-app/generate-app-overview.md
en/appbuilder/getting-started.md
en/appbuilder/indigo-design-app-builder-components.md
en/appbuilder/interactions.md
en/appbuilder/preview-code.md
en/appbuilder/single-page-apps-and-navigation.md
en/video-tutorials.md
jp/appbuilder/app-themes/app-themes.md
jp/appbuilder/flex-layouts/flex-layouts.md
jp/appbuilder/generate-app/generate-app-overview.md
jp/appbuilder/getting-started.md
jp/appbuilder/indigo-design-app-builder-components.md
jp/appbuilder/interactions.md
jp/appbuilder/preview-code.md
jp/appbuilder/single-page-apps-and-navigation.md
jp/video-tutorials.md

update videos markup to make them responsive.

---

en/appbuilder/generate-app/run-application-locally.md
en/appbuilder/preview-code.md
en/appbuilder/single-page-apps-and-navigation.md
en/codegen/after-codegen.md
en/components/card.md
en/components/column-chart.md
en/components/linear-gauge.md
en/components/spline-chart.md
en/components/step-line-chart.md
en/components/text.md
en/getting-started-old.md
en/global.json
en/sync-themes-plugin.md
package-lock.json
package.json

Add useWarningsAsErrors option -master

---

package-lock.json
package.json

Related to # https://github.com/IgniteUI/igniteui-docfx-template/issues/358

Update template version - master

---

package-lock.json
package.json

Related to # https://github.com/IgniteUI/igniteui-docfx/issues/2996

Update appbuilder navigation url

---

package-lock.json
package.json

Related to # https://github.com/IgniteUI/igniteui-docfx/issues/2996

Update template version- master

---

gulpfile.js

Related to #https://github.com/IgniteUI/indigo-design-docfx/issues/657

Replace environment variables

---

en/components/expansion-panel.md

Added info about the usage of the Expansion Panel component in Figma

Add info about Expansion Panel

---

en/components/icon.md

- Keywords for Figma
- Added information about Figma usage

Icon documentation refinement

---

en/components/calendar.md

- Updated info about the new `Week Numbers` property
- Renamed the `Type` property to `View`
- Renamed the `Show Header` property to `Header`

Calendar Update

---

en/components/time-picker.md

- Added information about the Header boolean property in Figma

Time Picker Update

---

en/components/rating.md

- added info about the Label boolean property
- Rating Value is now Value

Rating: Update

---

en/components/radio-group.md

- State has been switched for "Checked" boolean property

Radio Group: Update

---

en/components/stepper.md

- Added information about the Stepper Optional Step property and its purpose

Stepper: Update

---

en/components/checkbox.md

- New property Focused & Hover has been added

Checkbox: Update

---

en/components/accordion.md

- Removed Sketch references from accordion (en)
- Removed Adobe XD references from accordion (en)

[35167] Accordion: Remove Sketch and Adobe XD references (en)

---

en/components/avatar.md

1. Removed Sketch and Adobe XD references

[35168] Avatar: Remove Sketch and Adobe XD references (en)

---

en/components/button.md

1. Remove Sketch and Adobe XD references (en) in Button component

[35172] Button: Remove Sketch and Adobe XD references (en)

---

en/components/date-picker.md

1. Removed Sketch and Adobe XD references in Date Picker component

[35377] Date Picker: Remove Sketch and Adobe XD references (en)

---

en/components/dialog.md

1. Removed Sketch and Adobe XD references in Dialog component

[35378] Dialog: Remove Sketch and Adobe XD references (en)

---

en/components/divider.md

1. Removed Sketch and Adobe XD references in Divider component

[35408] Divider: Remove Sketch and Adobe XD references (en)

---

en/components/icon.md

1. Removed Sketch and Adobe XD references in Icon component

[35415] Icon: Remove Sketch and Adobe XD references (en)

---

en/components/input.md

1. Removed Sketch and Adobe XD references in Input component

[35416] Input: Remove Sketch and Adobe XD references (en)

---

en/components/navbar.md

1. Remove Sketch and Adobe XD references in Navbar component

[35418] Navbar: Remove Sketch and Adobe XD references (en)

---

en/components/time-picker.md

1. Removed Sketch and Adobe XD references in Time Picker component

[35431] Time Picker: Remove Sketch and Adobe XD references

---

en/components/snackbar.md

1. Removed Sketch and Adobe XD references from Snackbar component

[35425] Snackbar: Remove Sketch and Adobe XD references

---

en/known-issues.md

- remove Sketch and Adobe XD references

[35887] Known Issues: remove Sketch and Adobe XD references
